#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRFPacketDecoder
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LOLDB")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChampion(Champion instance);
    partial void UpdateChampion(Champion instance);
    partial void DeleteChampion(Champion instance);
    partial void InsertSpell(Spell instance);
    partial void UpdateSpell(Spell instance);
    partial void DeleteSpell(Spell instance);
    partial void InsertItem(Item instance);
    partial void UpdateItem(Item instance);
    partial void DeleteItem(Item instance);
    #endregion
		
		public DBDataContext() : 
				base(global::LRFPacketDecoder.Properties.Settings.Default.LOLDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Champion> Champions
		{
			get
			{
				return this.GetTable<Champion>();
			}
		}
		
		public System.Data.Linq.Table<Spell> Spells
		{
			get
			{
				return this.GetTable<Spell>();
			}
		}
		
		public System.Data.Linq.Table<Item> Items
		{
			get
			{
				return this.GetTable<Item>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Champions")]
	public partial class Champion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _ChampionID;
		
		private string _Name;
		
		private string _Description;
		
		private string _Tips1;
		
		private string _Tips2;
		
		private System.Nullable<double> _BaseHP;
		
		private System.Nullable<double> _BaseMP;
		
		private System.Nullable<double> _BaseDamage;
		
		private System.Nullable<double> _BaseCritChance;
		
		private System.Nullable<double> _BaseArmor;
		
		private System.Nullable<int> _BaseMoveSpeed;
		
		private System.Nullable<int> _BaseAttackRange;
		
		private System.Nullable<bool> _isMele;
		
		private string _Spell1Name;
		
		private string _Spell2Name;
		
		private string _Spell3Name;
		
		private string _Spell4Name;
		
		private string _FolderName;
		
		private string _ExtraSpell1;
		
		private string _ExtraSpell2;
		
		private string _ExtraSpell3;
		
		private string _ExtraSpell4;
		
		private string _ExtraSpell5;
		
		private string _ExtraSpell6;
		
		private string _ExtraSpell7;
		
		private string _ExtraSpell8;
		
		private string _ExtraSpell9;
		
		private string _ExtraSpell10;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnChampionIDChanging(System.Nullable<int> value);
    partial void OnChampionIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnTips1Changing(string value);
    partial void OnTips1Changed();
    partial void OnTips2Changing(string value);
    partial void OnTips2Changed();
    partial void OnBaseHPChanging(System.Nullable<double> value);
    partial void OnBaseHPChanged();
    partial void OnBaseMPChanging(System.Nullable<double> value);
    partial void OnBaseMPChanged();
    partial void OnBaseDamageChanging(System.Nullable<double> value);
    partial void OnBaseDamageChanged();
    partial void OnBaseCritChanceChanging(System.Nullable<double> value);
    partial void OnBaseCritChanceChanged();
    partial void OnBaseArmorChanging(System.Nullable<double> value);
    partial void OnBaseArmorChanged();
    partial void OnBaseMoveSpeedChanging(System.Nullable<int> value);
    partial void OnBaseMoveSpeedChanged();
    partial void OnBaseAttackRangeChanging(System.Nullable<int> value);
    partial void OnBaseAttackRangeChanged();
    partial void OnisMeleChanging(System.Nullable<bool> value);
    partial void OnisMeleChanged();
    partial void OnSpell1NameChanging(string value);
    partial void OnSpell1NameChanged();
    partial void OnSpell2NameChanging(string value);
    partial void OnSpell2NameChanged();
    partial void OnSpell3NameChanging(string value);
    partial void OnSpell3NameChanged();
    partial void OnSpell4NameChanging(string value);
    partial void OnSpell4NameChanged();
    partial void OnFolderNameChanging(string value);
    partial void OnFolderNameChanged();
    partial void OnExtraSpell1Changing(string value);
    partial void OnExtraSpell1Changed();
    partial void OnExtraSpell2Changing(string value);
    partial void OnExtraSpell2Changed();
    partial void OnExtraSpell3Changing(string value);
    partial void OnExtraSpell3Changed();
    partial void OnExtraSpell4Changing(string value);
    partial void OnExtraSpell4Changed();
    partial void OnExtraSpell5Changing(string value);
    partial void OnExtraSpell5Changed();
    partial void OnExtraSpell6Changing(string value);
    partial void OnExtraSpell6Changed();
    partial void OnExtraSpell7Changing(string value);
    partial void OnExtraSpell7Changed();
    partial void OnExtraSpell8Changing(string value);
    partial void OnExtraSpell8Changed();
    partial void OnExtraSpell9Changing(string value);
    partial void OnExtraSpell9Changed();
    partial void OnExtraSpell10Changing(string value);
    partial void OnExtraSpell10Changed();
    #endregion
		
		public Champion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChampionID", DbType="Int")]
		public System.Nullable<int> ChampionID
		{
			get
			{
				return this._ChampionID;
			}
			set
			{
				if ((this._ChampionID != value))
				{
					this.OnChampionIDChanging(value);
					this.SendPropertyChanging();
					this._ChampionID = value;
					this.SendPropertyChanged("ChampionID");
					this.OnChampionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(75)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(2500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tips1", DbType="VarChar(2500)")]
		public string Tips1
		{
			get
			{
				return this._Tips1;
			}
			set
			{
				if ((this._Tips1 != value))
				{
					this.OnTips1Changing(value);
					this.SendPropertyChanging();
					this._Tips1 = value;
					this.SendPropertyChanged("Tips1");
					this.OnTips1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tips2", DbType="VarChar(2500)")]
		public string Tips2
		{
			get
			{
				return this._Tips2;
			}
			set
			{
				if ((this._Tips2 != value))
				{
					this.OnTips2Changing(value);
					this.SendPropertyChanging();
					this._Tips2 = value;
					this.SendPropertyChanged("Tips2");
					this.OnTips2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseHP", DbType="Float")]
		public System.Nullable<double> BaseHP
		{
			get
			{
				return this._BaseHP;
			}
			set
			{
				if ((this._BaseHP != value))
				{
					this.OnBaseHPChanging(value);
					this.SendPropertyChanging();
					this._BaseHP = value;
					this.SendPropertyChanged("BaseHP");
					this.OnBaseHPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseMP", DbType="Float")]
		public System.Nullable<double> BaseMP
		{
			get
			{
				return this._BaseMP;
			}
			set
			{
				if ((this._BaseMP != value))
				{
					this.OnBaseMPChanging(value);
					this.SendPropertyChanging();
					this._BaseMP = value;
					this.SendPropertyChanged("BaseMP");
					this.OnBaseMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseDamage", DbType="Float")]
		public System.Nullable<double> BaseDamage
		{
			get
			{
				return this._BaseDamage;
			}
			set
			{
				if ((this._BaseDamage != value))
				{
					this.OnBaseDamageChanging(value);
					this.SendPropertyChanging();
					this._BaseDamage = value;
					this.SendPropertyChanged("BaseDamage");
					this.OnBaseDamageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseCritChance", DbType="Float")]
		public System.Nullable<double> BaseCritChance
		{
			get
			{
				return this._BaseCritChance;
			}
			set
			{
				if ((this._BaseCritChance != value))
				{
					this.OnBaseCritChanceChanging(value);
					this.SendPropertyChanging();
					this._BaseCritChance = value;
					this.SendPropertyChanged("BaseCritChance");
					this.OnBaseCritChanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseArmor", DbType="Float")]
		public System.Nullable<double> BaseArmor
		{
			get
			{
				return this._BaseArmor;
			}
			set
			{
				if ((this._BaseArmor != value))
				{
					this.OnBaseArmorChanging(value);
					this.SendPropertyChanging();
					this._BaseArmor = value;
					this.SendPropertyChanged("BaseArmor");
					this.OnBaseArmorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseMoveSpeed", DbType="Int")]
		public System.Nullable<int> BaseMoveSpeed
		{
			get
			{
				return this._BaseMoveSpeed;
			}
			set
			{
				if ((this._BaseMoveSpeed != value))
				{
					this.OnBaseMoveSpeedChanging(value);
					this.SendPropertyChanging();
					this._BaseMoveSpeed = value;
					this.SendPropertyChanged("BaseMoveSpeed");
					this.OnBaseMoveSpeedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseAttackRange", DbType="Int")]
		public System.Nullable<int> BaseAttackRange
		{
			get
			{
				return this._BaseAttackRange;
			}
			set
			{
				if ((this._BaseAttackRange != value))
				{
					this.OnBaseAttackRangeChanging(value);
					this.SendPropertyChanging();
					this._BaseAttackRange = value;
					this.SendPropertyChanged("BaseAttackRange");
					this.OnBaseAttackRangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isMele", DbType="Bit")]
		public System.Nullable<bool> isMele
		{
			get
			{
				return this._isMele;
			}
			set
			{
				if ((this._isMele != value))
				{
					this.OnisMeleChanging(value);
					this.SendPropertyChanging();
					this._isMele = value;
					this.SendPropertyChanged("isMele");
					this.OnisMeleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Spell1Name", DbType="VarChar(75)")]
		public string Spell1Name
		{
			get
			{
				return this._Spell1Name;
			}
			set
			{
				if ((this._Spell1Name != value))
				{
					this.OnSpell1NameChanging(value);
					this.SendPropertyChanging();
					this._Spell1Name = value;
					this.SendPropertyChanged("Spell1Name");
					this.OnSpell1NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Spell2Name", DbType="VarChar(75)")]
		public string Spell2Name
		{
			get
			{
				return this._Spell2Name;
			}
			set
			{
				if ((this._Spell2Name != value))
				{
					this.OnSpell2NameChanging(value);
					this.SendPropertyChanging();
					this._Spell2Name = value;
					this.SendPropertyChanged("Spell2Name");
					this.OnSpell2NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Spell3Name", DbType="VarChar(75)")]
		public string Spell3Name
		{
			get
			{
				return this._Spell3Name;
			}
			set
			{
				if ((this._Spell3Name != value))
				{
					this.OnSpell3NameChanging(value);
					this.SendPropertyChanging();
					this._Spell3Name = value;
					this.SendPropertyChanged("Spell3Name");
					this.OnSpell3NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Spell4Name", DbType="VarChar(75)")]
		public string Spell4Name
		{
			get
			{
				return this._Spell4Name;
			}
			set
			{
				if ((this._Spell4Name != value))
				{
					this.OnSpell4NameChanging(value);
					this.SendPropertyChanging();
					this._Spell4Name = value;
					this.SendPropertyChanged("Spell4Name");
					this.OnSpell4NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FolderName", DbType="VarChar(75)")]
		public string FolderName
		{
			get
			{
				return this._FolderName;
			}
			set
			{
				if ((this._FolderName != value))
				{
					this.OnFolderNameChanging(value);
					this.SendPropertyChanging();
					this._FolderName = value;
					this.SendPropertyChanged("FolderName");
					this.OnFolderNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtraSpell1", DbType="VarChar(75)")]
		public string ExtraSpell1
		{
			get
			{
				return this._ExtraSpell1;
			}
			set
			{
				if ((this._ExtraSpell1 != value))
				{
					this.OnExtraSpell1Changing(value);
					this.SendPropertyChanging();
					this._ExtraSpell1 = value;
					this.SendPropertyChanged("ExtraSpell1");
					this.OnExtraSpell1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtraSpell2", DbType="VarChar(75)")]
		public string ExtraSpell2
		{
			get
			{
				return this._ExtraSpell2;
			}
			set
			{
				if ((this._ExtraSpell2 != value))
				{
					this.OnExtraSpell2Changing(value);
					this.SendPropertyChanging();
					this._ExtraSpell2 = value;
					this.SendPropertyChanged("ExtraSpell2");
					this.OnExtraSpell2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtraSpell3", DbType="VarChar(75)")]
		public string ExtraSpell3
		{
			get
			{
				return this._ExtraSpell3;
			}
			set
			{
				if ((this._ExtraSpell3 != value))
				{
					this.OnExtraSpell3Changing(value);
					this.SendPropertyChanging();
					this._ExtraSpell3 = value;
					this.SendPropertyChanged("ExtraSpell3");
					this.OnExtraSpell3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtraSpell4", DbType="VarChar(75)")]
		public string ExtraSpell4
		{
			get
			{
				return this._ExtraSpell4;
			}
			set
			{
				if ((this._ExtraSpell4 != value))
				{
					this.OnExtraSpell4Changing(value);
					this.SendPropertyChanging();
					this._ExtraSpell4 = value;
					this.SendPropertyChanged("ExtraSpell4");
					this.OnExtraSpell4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtraSpell5", DbType="VarChar(75)")]
		public string ExtraSpell5
		{
			get
			{
				return this._ExtraSpell5;
			}
			set
			{
				if ((this._ExtraSpell5 != value))
				{
					this.OnExtraSpell5Changing(value);
					this.SendPropertyChanging();
					this._ExtraSpell5 = value;
					this.SendPropertyChanged("ExtraSpell5");
					this.OnExtraSpell5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtraSpell6", DbType="VarChar(75)")]
		public string ExtraSpell6
		{
			get
			{
				return this._ExtraSpell6;
			}
			set
			{
				if ((this._ExtraSpell6 != value))
				{
					this.OnExtraSpell6Changing(value);
					this.SendPropertyChanging();
					this._ExtraSpell6 = value;
					this.SendPropertyChanged("ExtraSpell6");
					this.OnExtraSpell6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtraSpell7", DbType="VarChar(75)")]
		public string ExtraSpell7
		{
			get
			{
				return this._ExtraSpell7;
			}
			set
			{
				if ((this._ExtraSpell7 != value))
				{
					this.OnExtraSpell7Changing(value);
					this.SendPropertyChanging();
					this._ExtraSpell7 = value;
					this.SendPropertyChanged("ExtraSpell7");
					this.OnExtraSpell7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtraSpell8", DbType="VarChar(75)")]
		public string ExtraSpell8
		{
			get
			{
				return this._ExtraSpell8;
			}
			set
			{
				if ((this._ExtraSpell8 != value))
				{
					this.OnExtraSpell8Changing(value);
					this.SendPropertyChanging();
					this._ExtraSpell8 = value;
					this.SendPropertyChanged("ExtraSpell8");
					this.OnExtraSpell8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtraSpell9", DbType="VarChar(75)")]
		public string ExtraSpell9
		{
			get
			{
				return this._ExtraSpell9;
			}
			set
			{
				if ((this._ExtraSpell9 != value))
				{
					this.OnExtraSpell9Changing(value);
					this.SendPropertyChanging();
					this._ExtraSpell9 = value;
					this.SendPropertyChanged("ExtraSpell9");
					this.OnExtraSpell9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtraSpell10", DbType="VarChar(75)")]
		public string ExtraSpell10
		{
			get
			{
				return this._ExtraSpell10;
			}
			set
			{
				if ((this._ExtraSpell10 != value))
				{
					this.OnExtraSpell10Changing(value);
					this.SendPropertyChanging();
					this._ExtraSpell10 = value;
					this.SendPropertyChanged("ExtraSpell10");
					this.OnExtraSpell10Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Spells")]
	public partial class Spell : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _ChampionID;
		
		private System.Nullable<int> _HashID;
		
		private string _SpellName;
		
		private string _DisplayName;
		
		private string _Description;
		
		private string _DynamicTooltip;
		
		private string _AlternateName;
		
		private string _MissileEffect;
		
		private string _AnimationName;
		
		private string _TextFlags;
		
		private string _HitEffectName;
		
		private System.Nullable<int> _Flags;
		
		private System.Nullable<double> _CastRange;
		
		private string _InibinFileName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnChampionIDChanging(System.Nullable<int> value);
    partial void OnChampionIDChanged();
    partial void OnHashIDChanging(System.Nullable<int> value);
    partial void OnHashIDChanged();
    partial void OnSpellNameChanging(string value);
    partial void OnSpellNameChanged();
    partial void OnDisplayNameChanging(string value);
    partial void OnDisplayNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnDynamicTooltipChanging(string value);
    partial void OnDynamicTooltipChanged();
    partial void OnAlternateNameChanging(string value);
    partial void OnAlternateNameChanged();
    partial void OnMissileEffectChanging(string value);
    partial void OnMissileEffectChanged();
    partial void OnAnimationNameChanging(string value);
    partial void OnAnimationNameChanged();
    partial void OnTextFlagsChanging(string value);
    partial void OnTextFlagsChanged();
    partial void OnHitEffectNameChanging(string value);
    partial void OnHitEffectNameChanged();
    partial void OnFlagsChanging(System.Nullable<int> value);
    partial void OnFlagsChanged();
    partial void OnCastRangeChanging(System.Nullable<double> value);
    partial void OnCastRangeChanged();
    partial void OnInibinFileNameChanging(string value);
    partial void OnInibinFileNameChanged();
    #endregion
		
		public Spell()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChampionID", DbType="Int")]
		public System.Nullable<int> ChampionID
		{
			get
			{
				return this._ChampionID;
			}
			set
			{
				if ((this._ChampionID != value))
				{
					this.OnChampionIDChanging(value);
					this.SendPropertyChanging();
					this._ChampionID = value;
					this.SendPropertyChanged("ChampionID");
					this.OnChampionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HashID", DbType="Int")]
		public System.Nullable<int> HashID
		{
			get
			{
				return this._HashID;
			}
			set
			{
				if ((this._HashID != value))
				{
					this.OnHashIDChanging(value);
					this.SendPropertyChanging();
					this._HashID = value;
					this.SendPropertyChanged("HashID");
					this.OnHashIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpellName", DbType="VarChar(75)")]
		public string SpellName
		{
			get
			{
				return this._SpellName;
			}
			set
			{
				if ((this._SpellName != value))
				{
					this.OnSpellNameChanging(value);
					this.SendPropertyChanging();
					this._SpellName = value;
					this.SendPropertyChanged("SpellName");
					this.OnSpellNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayName", DbType="VarChar(500)")]
		public string DisplayName
		{
			get
			{
				return this._DisplayName;
			}
			set
			{
				if ((this._DisplayName != value))
				{
					this.OnDisplayNameChanging(value);
					this.SendPropertyChanging();
					this._DisplayName = value;
					this.SendPropertyChanged("DisplayName");
					this.OnDisplayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(1500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DynamicTooltip", DbType="VarChar(1500)")]
		public string DynamicTooltip
		{
			get
			{
				return this._DynamicTooltip;
			}
			set
			{
				if ((this._DynamicTooltip != value))
				{
					this.OnDynamicTooltipChanging(value);
					this.SendPropertyChanging();
					this._DynamicTooltip = value;
					this.SendPropertyChanged("DynamicTooltip");
					this.OnDynamicTooltipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlternateName", DbType="VarChar(150)")]
		public string AlternateName
		{
			get
			{
				return this._AlternateName;
			}
			set
			{
				if ((this._AlternateName != value))
				{
					this.OnAlternateNameChanging(value);
					this.SendPropertyChanging();
					this._AlternateName = value;
					this.SendPropertyChanged("AlternateName");
					this.OnAlternateNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MissileEffect", DbType="VarChar(150)")]
		public string MissileEffect
		{
			get
			{
				return this._MissileEffect;
			}
			set
			{
				if ((this._MissileEffect != value))
				{
					this.OnMissileEffectChanging(value);
					this.SendPropertyChanging();
					this._MissileEffect = value;
					this.SendPropertyChanged("MissileEffect");
					this.OnMissileEffectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnimationName", DbType="VarChar(150)")]
		public string AnimationName
		{
			get
			{
				return this._AnimationName;
			}
			set
			{
				if ((this._AnimationName != value))
				{
					this.OnAnimationNameChanging(value);
					this.SendPropertyChanging();
					this._AnimationName = value;
					this.SendPropertyChanged("AnimationName");
					this.OnAnimationNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextFlags", DbType="VarChar(200)")]
		public string TextFlags
		{
			get
			{
				return this._TextFlags;
			}
			set
			{
				if ((this._TextFlags != value))
				{
					this.OnTextFlagsChanging(value);
					this.SendPropertyChanging();
					this._TextFlags = value;
					this.SendPropertyChanged("TextFlags");
					this.OnTextFlagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HitEffectName", DbType="VarChar(150)")]
		public string HitEffectName
		{
			get
			{
				return this._HitEffectName;
			}
			set
			{
				if ((this._HitEffectName != value))
				{
					this.OnHitEffectNameChanging(value);
					this.SendPropertyChanging();
					this._HitEffectName = value;
					this.SendPropertyChanged("HitEffectName");
					this.OnHitEffectNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flags", DbType="Int")]
		public System.Nullable<int> Flags
		{
			get
			{
				return this._Flags;
			}
			set
			{
				if ((this._Flags != value))
				{
					this.OnFlagsChanging(value);
					this.SendPropertyChanging();
					this._Flags = value;
					this.SendPropertyChanged("Flags");
					this.OnFlagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CastRange", DbType="Float")]
		public System.Nullable<double> CastRange
		{
			get
			{
				return this._CastRange;
			}
			set
			{
				if ((this._CastRange != value))
				{
					this.OnCastRangeChanging(value);
					this.SendPropertyChanging();
					this._CastRange = value;
					this.SendPropertyChanged("CastRange");
					this.OnCastRangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InibinFileName", DbType="VarChar(75)")]
		public string InibinFileName
		{
			get
			{
				return this._InibinFileName;
			}
			set
			{
				if ((this._InibinFileName != value))
				{
					this.OnInibinFileNameChanging(value);
					this.SendPropertyChanging();
					this._InibinFileName = value;
					this.SendPropertyChanged("InibinFileName");
					this.OnInibinFileNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Items")]
	public partial class Item : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _ItemID;
		
		private string _Name;
		
		private string _Description;
		
		private string _DynamicTooltip;
		
		private string _SpellName;
		
		private string _Icon;
		
		private string _FileName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnItemIDChanging(System.Nullable<int> value);
    partial void OnItemIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnDynamicTooltipChanging(string value);
    partial void OnDynamicTooltipChanged();
    partial void OnSpellNameChanging(string value);
    partial void OnSpellNameChanged();
    partial void OnIconChanging(string value);
    partial void OnIconChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    #endregion
		
		public Item()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemID", DbType="Int")]
		public System.Nullable<int> ItemID
		{
			get
			{
				return this._ItemID;
			}
			set
			{
				if ((this._ItemID != value))
				{
					this.OnItemIDChanging(value);
					this.SendPropertyChanging();
					this._ItemID = value;
					this.SendPropertyChanged("ItemID");
					this.OnItemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(75)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(1000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DynamicTooltip", DbType="VarChar(5000)")]
		public string DynamicTooltip
		{
			get
			{
				return this._DynamicTooltip;
			}
			set
			{
				if ((this._DynamicTooltip != value))
				{
					this.OnDynamicTooltipChanging(value);
					this.SendPropertyChanging();
					this._DynamicTooltip = value;
					this.SendPropertyChanged("DynamicTooltip");
					this.OnDynamicTooltipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpellName", DbType="VarChar(75)")]
		public string SpellName
		{
			get
			{
				return this._SpellName;
			}
			set
			{
				if ((this._SpellName != value))
				{
					this.OnSpellNameChanging(value);
					this.SendPropertyChanging();
					this._SpellName = value;
					this.SendPropertyChanged("SpellName");
					this.OnSpellNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icon", DbType="VarChar(75)")]
		public string Icon
		{
			get
			{
				return this._Icon;
			}
			set
			{
				if ((this._Icon != value))
				{
					this.OnIconChanging(value);
					this.SendPropertyChanging();
					this._Icon = value;
					this.SendPropertyChanged("Icon");
					this.OnIconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(75)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
